# Generated by Django 4.2.6 on 2023-10-27 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivilegeGroup',
            fields=[
                ('privilegeid', models.AutoField(db_column='PrivilegeID', primary_key=True, serialize=False)),
                ('groupname', models.TextField(db_column='GroupName')),
            ],
            options={
                'db_table': 'privilege_group',
            },
        ),
        migrations.CreateModel(
            name='TrialOrganisation',
            fields=[
                ('organisationid', models.AutoField(db_column='OrganisationID', primary_key=True, serialize=False)),
                ('organisationname', models.TextField(db_column='OrganisationName')),
                ('contactnumber', models.TextField(db_column='ContactNumber')),
            ],
            options={
                'db_table': 'trial_organisation',
            },
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('trialid', models.AutoField(db_column='TrialID', primary_key=True, serialize=False)),
                ('trialname', models.CharField(db_column='TrialName', max_length=255)),
                ('trialdescription', models.TextField(db_column='Description')),
                ('status', models.CharField(db_column='Status', max_length=15)),
                ('datecreated', models.DateField(auto_now_add=True, db_column='DateCreated')),
                ('organisationid', models.ForeignKey(db_column='OrganisationID', on_delete=django.db.models.deletion.CASCADE, to='db.trialorganisation')),
            ],
            options={
                'db_table': 'trial',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staffid', models.AutoField(db_column='StaffID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='FirstName', max_length=255)),
                ('lastname', models.CharField(db_column='LastName', max_length=255)),
                ('privilegeid', models.ForeignKey(db_column='PrivilegeID', on_delete=django.db.models.deletion.CASCADE, to='db.privilegegroup')),
                ('trials', models.ManyToManyField(to='db.trial')),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientid', models.AutoField(db_column='PatientID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='FirstName', max_length=255)),
                ('lastname', models.CharField(db_column='LastName', max_length=255)),
                ('m_gender', models.BooleanField(db_column='M_Gender')),
                ('dateofbirth', models.DateField(db_column='DateOfBirth')),
                ('trialid', models.ForeignKey(db_column='TrialID', on_delete=django.db.models.deletion.CASCADE, to='db.trial')),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('observationid', models.AutoField(db_column='ObservationID', primary_key=True, serialize=False)),
                ('description', models.TextField(db_column='Description')),
                ('date', models.DateTimeField(auto_now_add=True, db_column='DateCreated')),
                ('treatment', models.TextField(db_column='Treatment')),
                ('patientid', models.ForeignKey(db_column='PatientID', on_delete=django.db.models.deletion.CASCADE, to='db.patient')),
                ('staffid', models.ForeignKey(db_column='StaffID', on_delete=django.db.models.deletion.CASCADE, to='db.staff')),
                ('trialid', models.ForeignKey(db_column='TrialID', on_delete=django.db.models.deletion.CASCADE, to='db.trial')),
            ],
            options={
                'db_table': 'observation',
            },
        ),
    ]
